version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
    # Ne touchez pas à cette section sauf si vous avez des besoins spécifiques.
    # Caddy gère automatiquement la configuration SSL et la redirection HTTPS.

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files
    # Cette configuration ne doit pas être modifiée si vous suivez les instructions de base.
    # Les variables d'environnement sont gérées par le fichier `.env` et Coolify.

volumes:
  caddy_data:
    external: true
  n8n_data:
    external: true
